##00. PyTorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


##Introduction to Tensors

### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that
they start with tensors full of random numbers and then adjust those random numbers
to better represent the data.

Start with random numbers -> look at data -> update the random numbers

Torch random tensors - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
#Create a random tensor of size (2,3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.0908, 0.1643, 0.6973, 0.7667],
         [0.0231, 0.7773, 0.6625, 0.9388],
         [0.8385, 0.4536, 0.9922, 0.8354]],

        [[0.5185, 0.5464, 0.1671, 0.8109],
         [0.5298, 0.4236, 0.7310, 0.3747],
         [0.3079, 0.3241, 0.7215, 0.4448]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(224,224,3) #height, width, color channels (R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [ ]:
# Creating a tensor of all zeros or all ones
zeros = torch.zeros(2,3,4)
ones = torch.ones(2,3,4)
zeros, ones

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]))

In [ ]:
zeros * random_tensor, ones * random_tensor

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 tensor([[[0.0908, 0.1643, 0.6973, 0.7667],
          [0.0231, 0.7773, 0.6625, 0.9388],
          [0.8385, 0.4536, 0.9922, 0.8354]],
 
         [[0.5185, 0.5464, 0.1671, 0.8109],
          [0.5298, 0.4236, 0.7310, 0.3747],
          [0.3079, 0.3241, 0.7215, 0.4448]]]))

In [ ]:
ones.dtype

torch.float32

### Creating a range of Tensors and Tensors-like

In [ ]:
#Use torch.arange
one_to_fifteen = torch.arange(start = 1, end = 21, step = 2)
one_to_fifteen

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# Creating tensors like (for eg like one_to_fifteen)
ten_zeros = torch.zeros_like(one_to_fifteen)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatypes

Tensor datatypes - https://docs.pytorch.org/docs/stable/tensors.html

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None, # by default "cpu", can be "cuda" if tens on a diff device
                               requires_grad = False) #tracking gradients with tensors operations
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
x = float_16_tensor * float_32_tensor
x, x.dtype

(tensor([ 9., 36., 81.]), torch.float32)

###Getting info from Tensors

1. 'tensor.dtype'
2. 'tensor.shape'
3. 'tensor.device'

In [ ]:
some_tensor = torch.rand(2,3,4)
some_tensor

tensor([[[0.3205, 0.5657, 0.0572, 0.1091],
         [0.3497, 0.0268, 0.9621, 0.9051],
         [0.4245, 0.2054, 0.4499, 0.7655]],

        [[0.3784, 0.3382, 0.1069, 0.6944],
         [0.6897, 0.9823, 0.3821, 0.5536],
         [0.9354, 0.5735, 0.5768, 0.6924]]])

In [ ]:
print(some_tensor)
print(f"Datattype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[[0.3205, 0.5657, 0.0572, 0.1091],
         [0.3497, 0.0268, 0.9621, 0.9051],
         [0.4245, 0.2054, 0.4499, 0.7655]],

        [[0.3784, 0.3382, 0.1069, 0.6944],
         [0.6897, 0.9823, 0.3821, 0.5536],
         [0.9354, 0.5735, 0.5768, 0.6924]]])
Datattype of tensor: torch.float32
Shape of tensor: torch.Size([2, 3, 4])
Device tensor is on: cpu


###Manipulating Tensors (tensor operations)

Tensor operations include:
1. Addition, Subtraction, Multiplication (element-wise), Division
2. Matrix Multiplication

In [ ]:
#Create tensor and add 10 to it, multiply by 10
tens = torch.tensor([1,2,3])
tens += 10
tens-=10
tens

tensor([1, 2, 3])

In [ ]:
#Pytorch inbuilt functions
torch.mul(tens,10)
print(tens, "*", tens)
print(f"Equals: {tens * tens}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


###Matrix Multiplication

Two main ways of multiplication in NN and Deep Learning:
1. Element wise multiplication
2. Matrix Multiplication (dot product)


In [ ]:
# Matrix multiplication

torch.matmul(tens,tens)

tensor(14)

In [ ]:
%%time
val = 0
for i in range(len(tens)):
  val+=tens[i] * tens[i]
print(val)

tensor(14)
CPU times: user 1.29 ms, sys: 191 µs, total: 1.48 ms
Wall time: 3.6 ms


In [ ]:
%%time
torch.matmul(tens, tens)

CPU times: user 351 µs, sys: 51 µs, total: 402 µs
Wall time: 473 µs


tensor(14)

In [ ]:
x52 = torch.matmul(torch.rand(7,3), torch.rand(3,5))
x52

tensor([[2.1929, 0.7658, 0.7991, 1.6305, 1.9121],
        [1.4287, 0.6296, 0.4900, 0.8620, 1.0722],
        [1.2195, 0.4109, 0.4549, 0.8938, 1.1223],
        [1.5864, 0.5334, 0.5822, 1.2150, 1.4063],
        [1.1679, 0.4614, 0.3935, 0.8872, 0.8377],
        [1.4114, 0.6087, 0.4812, 0.9028, 1.0433],
        [1.0303, 0.3971, 0.3655, 0.7149, 0.8422]])

In [ ]:
x52.shape

torch.Size([7, 5])

In [ ]:
# Shapes for matrix multiplication
tensorA = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensorB = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
# torch.mm = torch.matmul
tensorA.shape, tensorB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
# Transpose
tensorB = tensorB.T

In [ ]:
torch.matmul(tensorA, tensorB), tensorB.shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([2, 3]))

In [ ]:
print(f"Output shape = {torch.matmul(tensorA, tensorB).shape}")

Output shape = torch.Size([3, 3])


## Finding the min, max, mean, sum, etc(tensor aggregation)

In [ ]:
#create a tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
x.min(), torch.max(x) #also torch.min(x) or x.max()

(tensor(1), tensor(91))

In [ ]:
#Find the mean :- torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Find the sum
x.sum(), torch.sum(x)

(tensor(460), tensor(460))

## Finding the positional max and min


In [ ]:
# Find the position in tensor which has the minimum value with argmin() ->
# returns index position of target tensor where the minimum value occurs
x, x.argmin()

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), tensor(0))

In [ ]:
#max value index with argmax
x.argmax(), x[9]

(tensor(9), tensor(91))

## Reshaping, stacking, squeezing and unsqueezing tensors
-> Reshaping - reshapes an input tensor to a defined shape.

-> View - Return a view of an input tensor of certain shape but
          keep the same memory as the original tensor.

-> Stacking - Combine multiple tensors on top of each other(vstack) or side by side(hstack).

-> Squeeze - Removes all '1' dimensions from a tensor.

-> Unsqueeze - Add a '1' dimension to a target tensor.

-> Permute - Return a view of the input with dimensions permuted(swapped) in a certain way.


In [ ]:
#Let's create a tensor
import torch
x = torch.arange(1,13)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), torch.Size([12]))

In [ ]:
#Add an extra dimension
x_reshaped = x.reshape(3,4)
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]),
 torch.Size([3, 4]))

In [ ]:
#Change the view
z = x.view(1,12)
z,z.shape, x, x.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 torch.Size([1, 12]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 torch.Size([12]))

In [ ]:
#Changing z changes x
 # (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z,x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 0)
x1_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked, x1_stacked

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
         [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
         [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
         [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 tensor([[ 5,  5,  5,  5],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3],
         [ 4,  4,  4,  4],
         [ 5,  5,  5,  5],
         [ 6,  6,  6,  6],
         [ 7,  7,  7,  7],
         [ 8,  8,  8,  8],
         [ 9,  9,  9,  9],
         [10, 10, 10, 10],
         [11, 11, 11, 11],
         [12, 12, 12, 12]]))

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped = x_reshaped.reshape(1,12)
x_reshaped, x_reshaped.shape

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]]),
 torch.Size([1, 12]))

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor shape: {x_reshaped.shape}")

#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New tensor shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
Previous tensor shape: torch.Size([1, 12])

New tensor: tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
New tensor shape: torch.Size([12])


In [ ]:
# torch.unsqueeze() - Adds a single dimension to a target tensor at a specific dimension
print(f"\nPrevious tensor: {x_squeezed}")
print(f"Previous tensor shape: {x_squeezed.shape}")

#Adds extra dimension to x_squeezed
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed1 = x_squeezed.unsqueeze(dim = 1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New tensor shape: {x_unsqueezed.shape}")

#print(f"\nNew tensor: {x_unsqueezed1}")
#print(f"New tensor shape: {x_unsqueezed1.shape}")



Previous tensor: tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
Previous tensor shape: torch.Size([12])

New tensor: tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
New tensor shape: torch.Size([1, 12])


In [ ]:
#torch.permute rearranges the dimensions of a target tensor in a specified order
x_org = torch.randn(224,224,3) # [height, width, colour_channels] of an image

#Permute the original tensor to rearrange the axis (or dim) order
#[cc, h, w]
#Permute shares the same memory as x original
x_permuted = torch.permute(x_org,(2,0,1)) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_org.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
print(f"Previous value: {x_org[0, 0, 0]}")
x_org[0, 0, 0] = 322
print(f"New value: {x_permuted[0, 0, 0]}")

Previous value: 0.5800561904907227
New value: 322.0


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1,19).reshape(2,3,3)
x, x.shape

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]],
 
         [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]]),
 torch.Size([2, 3, 3]))

In [ ]:
# Let's index on our first tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# indexing on middle bracket
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
#most inner bracket
x[0][2][2], x[0, 2 ,2]

(tensor(9), tensor(9))

In [ ]:
#Use : to select all of a target dimension
x[:, 0]

tensor([[ 1,  2,  3],
        [10, 11, 12]])

In [ ]:
#Get all values of 0th and 1st dimesnions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[ 2,  5,  8],
        [11, 14, 17]])

In [ ]:
#Get all values of 0th dimension but only the 1 index value of 1st of 2nd dimension
x[:, 1, 1]

tensor([ 5, 14])

In [ ]:
#Get index 0 of 0th and 1st dimension but all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
#Index on x to return 9
x[0, 2, 2]

tensor(9)

In [ ]:
#index on x to return [3,6,9]
x[0, :, 2]

tensor([3, 6, 9])

## Pytorch tensors and Numpy

NumPy is a popular scientific numerical computing library

And because of this, PyTorch has a functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0) #by default float 64
tensor = torch.from_numpy(array)
#tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
torch.arange(1.0, 8.0).dtype #default torch.float32

torch.float32

In [ ]:
#Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#change the tensor, what happens to np tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns is

* start with random numbers -> tensor operations -> update them to make them better representations of the data -> repeat

* To reduce the randomness in NNs and pytorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness. (Pseudorandomness)

Extra resources - https://docs.pytorch.org/docs/stable/notes/randomness.html

Wiki - https://en.wikipedia.org/wiki/Random_seed

In [ ]:
torch.rand(3,3) #every time new numbers

tensor([[0.9375, 0.3727, 0.1429],
        [0.4040, 0.6473, 0.8496],
        [0.2298, 0.7071, 0.1987]])

In [ ]:
import torch

# Create two random tensors
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.7017, 0.4423, 0.1073, 0.3285],
        [0.1962, 0.1404, 0.8951, 0.6453],
        [0.9094, 0.7168, 0.3710, 0.0684]])
tensor([[0.2929, 0.3347, 0.3654, 0.6987],
        [0.9204, 0.0519, 0.9770, 0.9388],
        [0.5332, 0.5998, 0.1037, 0.3373]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computation)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).


### 1. Getting a GPU

1. Easiest - Use google collab for a free GPU (options to upgrade as well)
2. Use your own GPU - a little bit of setup and purchasing a gpu (timdettmers post)
3. Use cloud computing - GCP, AWS, Azure (rent computers on cloud and use them)

For 2,3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this refer to PyTorch setup documentation - https://pytorch.org/get-started/locally/


In [ ]:
!nvidia-smi

Fri Oct  3 13:21:39 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnotic code - https://docs.pytorch.org/docs/stable/notes/cuda.html

Eg. run on GPU if available, else default to CPU

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors and models on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster calculations

In [ ]:
# Create a tesnor (default on the GPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to gpu if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu
# 0 is the index of device

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the cpu (because numpy online works on cpu)

In [ ]:
# If tensor is on GPU, can't transform it to numpy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

In [ ]:
tensor_on_gpu

In [ ]:
# Create a random (7,7) tensor
torch.manual_seed(0)
t1 = torch.randn(size = (7,7), dtype = torch.float32)
t1, t1.shape

In [ ]:
t2 = torch.randn(1,7)
t3 = torch.matmul(t1, t2.T)
t2, t3, t3.shape

In [ ]:
torch.cuda.manual_seed(1234)
device = "cuda" if torch.cuda.is_available() else "cpu"
device

In [ ]:
torch.manual_seed(1234)

ten1 = torch.randn(2,3).to(device)
ten2 = torch.randn(2,3).to(device)

mm = torch.matmul(ten1, ten2.T)
ten1, ten2, mm

In [ ]:
torch.max(mm), torch.min(mm)

In [ ]:
torch.argmax(mm), torch.argmin(mm)

In [ ]:
torch.manual_seed(7)
ran = torch.randn(1,1,1,10)
r1 = torch.squeeze(ran)
ran, ran.shape, r1, r1.shape

### THE END OF NOTEBOOK 1